api:
  duel_links_meta:
    base_url: https://www.duellinksmeta.com/api/v1
    user_agent: IP:Masquerena
    cache_ttl: 3600

  master_duel_meta:
    base_url: https://www.masterduelmeta.com/api/v1
    user_agent: IP:Masquerena
    cache_ttl: 3600

  ygoprodeck:
    base_url: https://db.ygoprodeck.com/api/v7
    cache_ttl: 86400

  bonk:
    url: http://localhost:3000/order/list
    auth_token: test-token

images:
  base_url: https://s3.lain.dev/ygo
  imaginary_url: https://imaginary.lain.dev/pipeline
  remote_base_url: https://images.ygoprodeck.com/images/cards
  remote_cropped_url: https://images.ygoprodeck.com/images/cards_cropped

cache:
  card_ttl: 3600
  set_ttl: 3600
  image_ttl: 86400
  search_ttl: 300

updates:
  interval: 120
  retry_delay: 300

formats:
  default: paper
  available:
    - paper
    - md
    - dl
    - sd

rate_limits:
  dlm: 100
  mdm: 100
  ygopro: 20
  images: 50

embeds:
  colors:
    spell: 0x1DA353
    trap: 0xBC5A84
    skill: 0x6694
    monster:
      normal: 0xE4C77B
      effect: 0xB85C1C
      fusion: 0x7E1DDB
      ritual: 0x2A5B98
      synchro: 0xBEBEBE
      xyz: 0x000000
      link: 0x00008B
      pendulum: 0x40E0D0

  icons:
    spell: "<:spell:948992874438070342>"
    trap: "<:trap:948992874438074428>"
    attributes:
      DARK: "<:DARK:948992874400346152>"
      DIVINE: "<:DIVINE:948992874089947136>"
      EARTH: "<:EARTH:948992874442285096>"
      FIRE: "<:FIRE:948992874375176212>"
      LIGHT: "<:LIGHT:948992874396151879>"
      WATER: "<:WATER:948992874136096768>"
      WIND: "<:WIND:948992874123505775>"

errors:
  not_found: "Couldn't find that card. Check your spelling and try again."
  rate_limit: "Please wait before trying again."
  network: "There was a problem connecting to the service. Please try again later."
  no_image: "Card image not available."
  no_ocg_access: "You don't have access to OCG art. Support the bot to gain access!"
  invalid_format: "Invalid format. Available formats: paper, md, dl, sd"
